---
abstract: 'utility methods to apply to Moose type constraints'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::Modern: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
dynamic_config: 1
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.023, CPAN::Meta::Converter version 2.142690'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MooseX-Types-MoreUtils
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  Moose::Util::TypeConstraints:
    file: lib/MooseX/Types/MoreUtils.pm
  MooseX::Types::MoreUtils:
    file: lib/MooseX/Types/MoreUtils.pm
    version: '0.001'
recommends:
  B::Hooks::Parser: '0'
  Moose: '2.0600'
requires:
  List::Util: '1.29'
  perl: '5.008001'
resources:
  IRC: irc://irc.perl.org/#moose
  Identifier: http://purl.org/NET/cpan-uri/dist/MooseX-Types-MoreUtils/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=MooseX-Types-MoreUtils
  homepage: https://metacpan.org/release/MooseX-Types-MoreUtils
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tobyink/p5-moosex-types-moreutils.git
version: '0.001'
